const bcrypt = require("bcrypt");
const User = require("../models/User");
const Job = require("../models/Job");
const Experience = require("../models/Experience");

const sampleCompanies = [
  {
    title: "SDE Intern",
    company: "Oracle",
    location: "Bengaluru",
    type: "Internship",
    salary: "8-12 LPA",
    description: "Backend-heavy internship with OA, technical interviews, and strong focus on DSA plus CS fundamentals.",
    tags: ["Java", "SQL", "REST API", "Spring Boot"],
    eligibleBranches: ["CS", "EE", "ECE"],
    minCGPA: 7.5,
    typicalRounds: ["OA", "Technical Round 1", "Technical Round 2", "HR"],
    ctcRange: { min: 8, max: 12 },
    driveType: "on-campus",
    expectedDriveMonth: "July 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["Arrays", "DP", "OS", "DBMS"],
    difficulty: "Medium",
  },
  {
    title: "Associate Software Engineer",
    company: "MathWorks",
    location: "Hyderabad",
    type: "Full-time",
    salary: "14-18 LPA",
    description: "Strong problem solving and C++/system design oriented campus role.",
    tags: ["C++", "Algorithms", "System Design", "OOP"],
    eligibleBranches: ["CS", "ECE"],
    minCGPA: 8,
    typicalRounds: ["OA", "Technical Round 1", "Technical Round 2", "HR"],
    ctcRange: { min: 14, max: 18 },
    driveType: "on-campus",
    expectedDriveMonth: "August 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["Graphs", "DP", "System Design", "OOP"],
    difficulty: "Hard",
  },
  {
    title: "Software Engineer",
    company: "BlackRock",
    location: "Gurugram",
    type: "Full-time",
    salary: "12-16 LPA",
    description: "Fintech campus role emphasizing DSA, Java, and strong CS basics.",
    tags: ["Java", "Spring Boot", "DBMS", "CN"],
    eligibleBranches: ["CS", "EE", "ECE"],
    minCGPA: 7,
    typicalRounds: ["OA", "Technical Round 1", "HR"],
    ctcRange: { min: 12, max: 16 },
    driveType: "on-campus",
    expectedDriveMonth: "September 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["Arrays", "Trees", "OS", "DBMS"],
    difficulty: "Medium",
  },
  {
    title: "Graduate Engineer Trainee",
    company: "Texas Instruments",
    location: "Bengaluru",
    type: "Full-time",
    salary: "11-15 LPA",
    description: "Electronics and embedded oriented campus opportunity with aptitude plus technical rounds.",
    tags: ["Embedded", "C", "Python"],
    eligibleBranches: ["EE", "ECE"],
    minCGPA: 7.5,
    typicalRounds: ["OA", "Technical Round 1", "Technical Round 2", "HR"],
    ctcRange: { min: 11, max: 15 },
    driveType: "on-campus",
    expectedDriveMonth: "August 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["C", "Pointers", "Microcontrollers", "Signals"],
    difficulty: "Hard",
  },
  {
    title: "SWE Intern",
    company: "Atlassian",
    location: "Remote",
    type: "Internship",
    salary: "20-24 LPA",
    description: "High-bar internship with strong emphasis on coding rounds and backend design.",
    tags: ["Java", "Microservices", "System Design", "SQL"],
    eligibleBranches: ["CS", "ECE"],
    minCGPA: 7,
    typicalRounds: ["OA", "Technical Round 1", "Technical Round 2", "Managerial"],
    ctcRange: { min: 20, max: 24 },
    driveType: "off-campus",
    expectedDriveMonth: "July 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["Graphs", "LLD", "DBMS", "Concurrency"],
    difficulty: "Hard",
  },
  {
    title: "Software Developer",
    company: "ZS Associates",
    location: "Pune",
    type: "Full-time",
    salary: "10-13 LPA",
    description: "Campus hiring for analytics and engineering with OA, case discussion, and interviews.",
    tags: ["Python", "SQL", "Analytics"],
    eligibleBranches: ["CS", "EE", "ECE", "ME", "CE"],
    minCGPA: 6.5,
    typicalRounds: ["OA", "Case Round", "Technical", "HR"],
    ctcRange: { min: 10, max: 13 },
    driveType: "pool",
    expectedDriveMonth: "September 2025",
    allowsAllBranches: true,
    historicallyVisited: true,
    topicsAsked: ["SQL", "Probability", "Case Study"],
    difficulty: "Medium",
  },
  {
    title: "Product Engineer",
    company: "Sprinklr",
    location: "Gurugram",
    type: "Full-time",
    salary: "18-22 LPA",
    description: "Backend and product engineering role focusing on DSA, databases, and distributed systems basics.",
    tags: ["Java", "Redis", "Kafka", "System Design"],
    eligibleBranches: ["CS", "EE", "ECE"],
    minCGPA: 7,
    typicalRounds: ["OA", "Technical Round 1", "Technical Round 2", "HR"],
    ctcRange: { min: 18, max: 22 },
    driveType: "on-campus",
    expectedDriveMonth: "October 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["Arrays", "DBMS", "System Design", "OS"],
    difficulty: "Hard",
  },
  {
    title: "Analyst Programmer",
    company: "Wells Fargo",
    location: "Hyderabad",
    type: "Full-time",
    salary: "13-15 LPA",
    description: "Engineering analyst role with SQL, Java, and CS fundamentals focus.",
    tags: ["Java", "SQL", "Spring Boot"],
    eligibleBranches: ["CS", "EE", "ECE", "ME"],
    minCGPA: 7,
    typicalRounds: ["OA", "Technical", "HR"],
    ctcRange: { min: 13, max: 15 },
    driveType: "on-campus",
    expectedDriveMonth: "September 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["SQL", "OS", "DBMS", "Java"],
    difficulty: "Medium",
  },
  {
    title: "SDE 1",
    company: "CRED",
    location: "Bengaluru",
    type: "Full-time",
    salary: "18-20 LPA",
    description: "Fast-paced startup role with strong backend and product thinking expectations.",
    tags: ["Node.js", "TypeScript", "PostgreSQL", "Redis"],
    eligibleBranches: ["CS", "ECE"],
    minCGPA: 7,
    typicalRounds: ["Assignment", "Technical Round 1", "Technical Round 2", "Culture"],
    ctcRange: { min: 18, max: 20 },
    driveType: "off-campus",
    expectedDriveMonth: "November 2025",
    allowsAllBranches: false,
    historicallyVisited: false,
    topicsAsked: ["Node.js", "PostgreSQL", "System Design", "API"],
    difficulty: "Hard",
  },
  {
    title: "Graduate Trainee Engineer",
    company: "L&T Technology Services",
    location: "Mysuru",
    type: "Full-time",
    salary: "6-8 LPA",
    description: "Core engineering campus role with aptitude, branch basics, and interview rounds.",
    tags: ["Core Subjects", "Aptitude"],
    eligibleBranches: ["EE", "ECE", "ME", "CE"],
    minCGPA: 6,
    typicalRounds: ["OA", "Technical", "HR"],
    ctcRange: { min: 6, max: 8 },
    driveType: "on-campus",
    expectedDriveMonth: "July 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["Circuits", "Machines", "Aptitude"],
    difficulty: "Easy",
  },
  {
    title: "Software Development Intern",
    company: "Nagarro",
    location: "Remote",
    type: "Internship",
    salary: "7-10 LPA",
    description: "Remote internship with web stack focus and practical coding rounds.",
    tags: ["React", "Node.js", "MongoDB", "Docker"],
    eligibleBranches: ["CS", "EE", "ECE", "CE"],
    minCGPA: 6.5,
    typicalRounds: ["OA", "Technical", "HR"],
    ctcRange: { min: 7, max: 10 },
    driveType: "pool",
    expectedDriveMonth: "August 2025",
    allowsAllBranches: false,
    historicallyVisited: true,
    topicsAsked: ["React", "REST API", "MongoDB", "Docker"],
    difficulty: "Medium",
  },
  {
    title: "Associate Developer",
    company: "Infosys InStep",
    location: "Bengaluru",
    type: "Internship",
    salary: "5-7 LPA",
    description: "Large volume campus internship with aptitude and coding rounds.",
    tags: ["Java", "Python", "Problem Solving"],
    eligibleBranches: ["CS", "EE", "ECE", "ME", "CE"],
    minCGPA: 6,
    typicalRounds: ["OA", "Interview"],
    ctcRange: { min: 5, max: 7 },
    driveType: "on-campus",
    expectedDriveMonth: "July 2025",
    allowsAllBranches: true,
    historicallyVisited: true,
    topicsAsked: ["Aptitude", "Arrays", "OOP"],
    difficulty: "Easy",
  },
];

const sampleExperiences = [
  {
    companyName: "Oracle",
    role: "SDE Intern",
    year: 2024,
    month: "July",
    branch: "CS",
    college: "NIT Raipur",
    outcome: "offer",
    rounds: [
      { roundType: "OA", description: "Two coding problems and SQL MCQs.", duration: "90 min" },
      { roundType: "Technical", description: "DP, trees, and resume deep dive.", duration: "45 min" },
      { roundType: "HR", description: "Team fit and internship expectations.", duration: "20 min" },
    ],
    topicsAsked: ["DP", "Trees", "SQL"],
    tips: "Practice medium LeetCode plus DBMS basics. They spent time on project trade-offs.",
    isAnonymous: true,
  },
  {
    companyName: "MathWorks",
    role: "Software Engineer",
    year: 2024,
    month: "August",
    branch: "ECE",
    college: "NIT Trichy",
    outcome: "reject",
    rounds: [
      { roundType: "OA", description: "Strong C++ and algorithmic problems.", duration: "120 min" },
      { roundType: "Technical", description: "System design lite and OOP concepts.", duration: "60 min" },
    ],
    topicsAsked: ["C++", "Graphs", "System Design"],
    tips: "Do not ignore OOP and STL details. Their OA is harder than average campus rounds.",
    isAnonymous: true,
  },
];

async function ensureSeedUser() {
  let user = await User.findOne({ email: "seed@placemate.app" });
  if (!user) {
    const passwordHash = await bcrypt.hash("PlaceMate123", 10);
    user = await User.create({
      email: "seed@placemate.app",
      passwordHash,
      name: "PlaceMate Seed",
      role: "admin",
      profileCompleted: true,
      studentProfile: {
        college: "NIT Sample",
        branch: "CS",
        year: 4,
        cgpa: 8.4,
        leetcodeRating: 1580,
        problemsSolved: 320,
        skills: ["React", "Node.js", "MongoDB", "TypeScript", "DBMS", "OS"],
        projectCount: 3,
        deployedProjectCount: 2,
        hasInternship: true,
        openSourceContributions: false,
        systemDesign: "basic",
        targetCompanies: ["Oracle", "MathWorks", "BlackRock"],
      },
    });
  }
  return user;
}

async function seedJobsIfEmpty() {
  const existingJobs = await Job.countDocuments();
  const seedUser = await ensureSeedUser();

  if (existingJobs === 0) {
    await Job.insertMany(
      sampleCompanies.map((company) => ({
        ...company,
        postedBy: seedUser._id,
        isActive: true,
      })),
    );
    console.log("Seeded sample company drives for PlaceMate.");
  }

  const existingExperiences = await Experience.countDocuments();
  if (existingExperiences === 0) {
    await Experience.insertMany(sampleExperiences);
    console.log("Seeded sample interview experiences for PlaceMate.");
  }
}

module.exports = { seedJobsIfEmpty };
